name: Release Documentation
on: [push]
jobs:
  build-and-release-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout website repo
        uses: actions/checkout@v2
        with:
          repository: xlrte/xlrte.github.io
          path: xlrte.github.io
      - name: Deploy website
        run: |
          ls -ltr
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
          path: main
      - run: npm install -g yarn
        with: 
          path: main
      - run: yarn
        with: 
          path: main
      - run: yarn build
        with: 
          path: main
      - name: Deploy website
        run: |
          ls -ltr
