name: Release Documentation
on: [push]
jobs:
  build-and-release-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn
    - run: yarn build
    - name: Checkout tools repo
      uses: actions/checkout@v2
      with:
        repository: xlrte/xlrte.github.io
        path: xlrte-web
    - name: Deploy website
      run: |
        cd xlrte-web
        find . -path ./.git -prune -o -exec rm -rf {} \; 2> /dev/null
        copy -r ../build/* .
        git add .
        git diff-index --quiet HEAD || git commit -m "Automatic publish from github.com/xlrte/website"
        git push origin main